model_params: 
  POI_file: 'inputs/bounding_box_1_poi_data.csv'
  Traffic_file: 'None'
  model_name :  'Bounding_box_1'
  rep_agents: 7000

agent_params: 
  EVs: 
    num_agents: 1000
  Charge_Points:
    CP_loc: 'inputs\bounding_box_1_charging_stations.csv'
